### ISSUE TITLE
Multiple Payment Processors

### ISSUE THREAD

**Issue by mcelaney** [aviabird/gringotts#112]
Gringotts works great but I can not rely on env config vars for API information as I have a need to allow for multiple payment processors on the same project.

My thinking is to have the define a module to use for acquiring the api info in an env var - which in turn could use the env vars if desired or alternatively determine the creds through some other means.

If I make that change is it something this project is interested in or should I fork and work this as a separate project?

**Comment by pkrawat1** [comment]
@mcelaney thanks for bringing this up. If I understood correctly you want to use multiple payment gateways in your application at the same time.  

I am happy to inform we have implemented this and you can very well check it in out in our [example repository](https://github.com/aviabird/gringotts_payment/blob/dev/config/config.exs). You can even check the demo [here](https://gringottspay.herokuapp.com/).

One thing I didn't understand is what is the problem with using env config for API information, at most you'll be having `api_key` & `api_secret` set as env vars and as per my limited understanding this is a very common use case why we have `env` vars in the first place. 

Let me know if I am missing something here?

**Comment by PragTob** [comment]
I think this can get closed :)
