### ISSUE TITLE
Fix "cyclomatic_complexity" issue in lib/mix/new.ex

### ISSUE THREAD

**Issue by pkrawat1** [aviabird/gringotts#158]
Function is too complex (CC is 11, max is 9).

https://codeclimate.com/github/aviabird/gringotts/lib/mix/new.ex#issue_5adc7bc78bb7620001000040

**Comment by barthr** [comment]
I would like to do this one if possible!

**Comment by ashish173** [comment]
@barthr yes please, this is still open and waiting to be picked.

**Comment by barthr** [comment]
Cool! I'm working on a PR which fixes some more credo errors in that particular file, I will submit it in a few hours!

**Comment by barthr** [comment]
I opened a PR which fixes these warnings, there is one code check which fails, but I think that it's not relevant to the PR.

**Comment by ashish173** [comment]
Fixed in #182
