### ISSUE TITLE
Choose between test and production url

### ISSUE THREAD

**Issue by arjun289** [aviabird/gringotts#18]
The merchant should have the flexibility to switch between test and the production url.
This is done so that they can use the test url to check their sandbox account, while the production url would be used for the main account.

The opts field will have the following key-value pair. Depending on this test or production url is set.
[ { mode: "test" } ]

**Comment by oyeb** [comment]
#29 by @arjun289 proposes a fix.

**Comment by pkrawat1** [comment]
#29 is merged now so closing this PR.
