### ISSUE TITLE
Argument error reporting for config passed from application is at run time change it to compile time

### ISSUE THREAD

**Issue by pkrawat1** [aviabird/gringotts#3]
Config related-error reporting was introduced in #7 and currently happens at runtime, before every call to Gringotts API.
We should validate the config at compile time to reduce the overhead.

**Comment by oyeb** [comment]
Hmm, this is do-able, but it can cause problems when the user explicitly wants to pass in some credentials or different config at run-time (for example in #41).
Moreover, the config may not be available at compile time if some service is going to populate it at runtime (imagine some custom deployment setup where these credentials are fetched from a remote resource).

Also, the `Application` config is designed to be really fast (it is [backed by `:ets`](https://elixirforum.com/t/choosing-between-keyword-arguments-and-config-values/923/7?u=oyeb)) so this is not really an overhead.
