### ISSUE TITLE
Handle network response error issue for the gateway calls

### ISSUE THREAD

**Issue by pkrawat1** [aviabird/gringotts#30]
When a network time out happens we need to handle that gracefully.

**Comment by oyeb** [comment]
How about a clause in our `respond` (or equivalent) methods which process the conversion of `HTTPoison.Response` to `Gringotts.Response`?
See an example right [here](https://github.com/aviabird/gringotts/blob/master/lib/gringotts/gateways/monei.ex#L301), and an associated [test](https://github.com/aviabird/gringotts/blob/master/test/gateways/monei_test.exs#L71).
```elixir
def respond({:error, %HTTPoison.Error{} = error}) do
  do_some_nice_handling
end
```
