### ISSUE TITLE
Change casing style for gateway config options to use elixir styling not gateway style.

### ISSUE THREAD

**Issue by pkrawat1** [aviabird/gringotts#39]
Currently, we are using the gateway expected case styling in the gateway config block in the application code. 

This introduces a lot of disparity in between the gateway configs. 

Proposal:-

*We have a common style and we create a map at gateway level in library to interface gateway keys with config application level keys.*

Changes to be made in all the existing gateways;
* Map all the application level config keys to the gateway specific keys and then send the request.
* any other changes?.. developing...

This would ensure that we have a consistent API for config.

**Comment by oyeb** [comment]
I'm sorry I don't understand the issue. Could you link to the offending code to make this clear?
What is "case styling"?

**Comment by oyeb** [comment]
Done :tada:
