### ISSUE TITLE
Support multiple workers for a gateway simultaneously.

### ISSUE THREAD

**Issue by pkrawat1** [aviabird/gringotts#4]
Currently, we have named workers which can only be one at a time and can be set in the config passed from the application.

This is only good when we have to run a worker at a time.

If we have to support multiple workers then either we have to move away from the named workers or use something like gproc etc which support that using ETS etc.

This was introduced in first_pass PR merge.

Some refs
https://www.amberbit.com/blog/2016/5/13/process-name-registration-in-elixir/ https://github.com/uwiger/gproc
https://m.alphasights.com/process-registry-in-elixir-a-practical-example-4500ee7c0dcc
https://medium.com/elixirlabs/registry-in-elixir-1-4-0-d6750fb5aeb
http://codeloveandboards.com/blog/2016/03/20/supervising-multiple-genserver-processes/

**Comment by oyeb** [comment]
No more workers in Gringotts! If you need some, use the standard constructs in elixir or some dedicated pooling library.
