### ISSUE TITLE
Remove `http` method from `Base` module.

### ISSUE THREAD

**Issue by pkrawat1** [aviabird/gringotts#5]
Refer stripe.ex
```elixir
{api_key, ""} passing this parameter as empty string does not make sense here.

defp commit(method, path, params, opts) do
    config = Keyword.fetch!(opts, :config)
    # TODO: credentials should be investigated why it is {api_key, ""}
    # Did to mimic the earlier behaviour.
    method
      |> http("#{@base_url}/#{path}", params, credentials: {config[:api_key], ""})
      |> respond
  end
```
Please do necessary investigation for this one and fix it.

Edit:
* [x] Remove `http` and money utils from `Base`
* [ ] Remove `random*` methods from `Bogus`

**Comment by oyeb** [comment]
There is no usage of the `http` method defined in [`base.ex`](https://github.com/aviabird/gringotts/blob/master/lib/gringotts/gateways/base.ex#L41).
Hence, I'm changing the purpose of this issue.
