### ISSUE TITLE
[paymill] Support more optional fields

### ISSUE THREAD

**Issue by SagarKarwande** [aviabird/gringotts#50]
Support all optional fields provided by Paymill

**Comment by oyeb** [comment]
Could you provide a link to that list of fields or the subset that is going to be supported?

**Comment by SagarKarwande** [comment]
As of now there is currency field. I have contacted with Paymill team for the list, as I did not find it on there website.

**Comment by oyeb** [comment]
Closed as Paymill does not have any optional fields, we've covered pretty much everything. :clap:
