### ISSUE TITLE
Currency list we are passing in config as string can be atoms

### ISSUE THREAD

**Issue by pkrawat1** [aviabird/gringotts#55]
Currently, we are passing currency as a string `"USD"` in the application config `:global_config`.

This can be improved to use atoms like `:usd` or something which can be driven and controlled by the library instead of a plane string.

**Comment by oyeb** [comment]
Atoms are best suited for keys (in a map or keyword), [as far as](http://blog.pemedeiros.com/elixir-atoms-are-everywhere/) I've [read](https://til.hashrocket.com/posts/b9giaqz4lc-current-number-of-atoms-in-the-atoms-table).
We'll have to convert these atoms to upcase strings when making requests to the gateway anyways. There's a [thread on elixirforum](https://elixirforum.com/t/serialisation-atoms/4879/14) discussing something serialisation and atoms.

**Comment by SagarKarwande** [comment]
As there is limit on atoms count in erlang. [link](https://til.hashrocket.com/posts/b9giaqz4lc-current-number-of-atoms-in-the-atoms-table)
 

- Though using atom for currency/country code will not increase atom count at great extent. But huge project may consider huge atom count for using library. 
- Also some gateway are using atoms for keys in the post body creation. So should we use string or atom there.

**Comment by oyeb** [comment]
This is now obsolete because of #62 and #71.
It's the Money lib's responsibility to provide a sane/nice interface to create Money objects.
