### ISSUE TITLE
Multiple clauses for purchase and authorize and match against the type of second arg in wirecard

### ISSUE THREAD

**Issue by pkrawat1** [aviabird/gringotts#6]
In wiredcard gateway inside authorize method we are trying to manipulate the options depending on type of payment method using method

check_and_return_payment_method(payment_method)

however same could be done by using pattern matching feature of elixir by creating two identical functions with params with diff type and pattern match the input params based on it.

**Comment by oyeb** [comment]
@kartikjagdale Hasn't this been fixed long back in 700a06b?

**Comment by kartikjagdale** [comment]
:+1:
