### ISSUE TITLE
[mix task] Needs test templates, tests

### ISSUE THREAD

**Issue by oyeb** [aviabird/gringotts#80]
## `gringotts.new`

Generates just a gateway implementation file, it should also create:
* `test/gateways/<gateway>_test.exs`
* `test/integration/gateways/<gateway>_test.exs`

Which mocking library do we endorse, [`bypass`](https://github.com/pspdfkit-labs/bypass) or [`mox`](https://github.com/plataformatec/mox) (I'm strongly against [`mock`](https://github.com/jjh42/mock))?

### Test coverage
The task has no coverage, take inspiration from [`phx.new`](https://github.com/phoenixframework/phoenix/blob/master/test/mix/tasks/phx.new_test.exs).

**Comment by pkrawat1** [comment]
I think [mox](https://github.com/plataformatec/mox) is a good option here.
